export const projects = [
  {
    id: 1,
    type: "Web Dev",
    title: "Responsive Website",
    description: "A responsive website using HTML, CSS, and JavaScript.",
    url: "https://www.youtube.com/watch?v=wzpx_d_nHfg",
  },
  {
    id: 2,
    type: "Web Dev",
    title: "E-commerce Site",
    description: "A full-featured e-commerce site using React and Node.js.",
    url: "https://github.com/basir/node-react-ecommerce",
  },
  {
    id: 3,
    type: "Web Dev",
    title: "Portfolio Website",
    description: "A personal portfolio website showcasing projects and skills.",
    url: "https://codewithcurious.com/projects/personal-portfolio-website/",
  },
  {
    id: 4,
    type: "Web Dev",
    title: "Blog Platform",
    description:
      "A blog platform with user authentication and content management.",
    url: "https://www.domainindia.com/login/knowledgebase/538/Designing-a-Personal-Blog-Platform-with-MERN-Stack.html",
  },
  {
    id: 5,
    type: "Web Dev",
    title: "Social Media App",
    description:
      "A social media platform for sharing posts and connecting with friends.",
    url: "https://github.com/Deshan555/Social-Media-Platform",
  },
  {
    id: 6,
    type: "Web Dev",
    title: "Task Manager",
    description: "A task management app to organize and prioritize tasks.",
    url: "https://github.com/topics/task-management-app?o=desc&s=stars",
  },
  {
    id: 7,
    type: "Web Dev",
    title: "Online Forum",
    description: "A forum platform for discussions and community engagement.",
    url: "https://github.com/mbeps/next_discussion_platform",
  },
  {
    id: 8,
    type: "Web Dev",
    title: "Job Portal",
    description: "A job portal for employers and job seekers.",
    url: "https://www.youtube.com/watch?v=zwpzwZIkF4Q",
  },
  {
    id: 9,
    type: "Web Dev",
    title: "Recipe Website",
    description: "A recipe website with user-generated content and reviews.",
    url: "https://www.isitwp.com/create-food-recipe-website/",
  },
  {
    id: 10,
    type: "Web Dev",
    title: "Online Learning Platform",
    description: "An online platform for courses and learning resources.",
    url: "https://github.com/topics/learning-management-system",
  },
  {
    id: 11,
    type: "Game Dev",
    title: "2D Platformer",
    description: "A fun 2D platformer game built with Unity.",
    url: "https://www.youtube.com/watch?v=teJnlVyOmag",
  },
  {
    id: 12,
    type: "Game Dev",
    title: "Puzzle Game",
    description: "A challenging puzzle game with multiple levels.",
    url: "https://github.com/karjonas/Puzzle-Moppet",
  },
  {
    id: 13,
    type: "Game Dev",
    title: "Endless Runner",
    description: "An endless runner game with procedurally generated levels.",
    url: "https://github.com/striderzz/Unity-Endless-Runner-Procedural-Generation",
  },
  {
    id: 14,
    type: "Game Dev",
    title: "Tower Defense",
    description: "A tower defense game with strategic gameplay.",
    url: "https://www.youtube.com/watch?v=C4_iRLlPNFc",
  },
  {
    id: 15,
    type: "Game Dev",
    title: "RPG Game",
    description: "A role-playing game with character progression and quests.",
    url: "https://github.com/Erikote04/Role-Playing-Game",
  },
  {
    id: 16,
    type: "Game Dev",
    title: "Card Game",
    description: "A digital card game with multiplayer support.",
    url: "https://github.com/mochatek/Numberoli",
  },
  {
    id: 17,
    type: "Game Dev",
    title: "Platform Fighter",
    description: "A platform fighting game with various characters and moves.",
    url: "https://github.com/SheteUC/basic-platform-fighter",
  },
  {
    id: 18,
    type: "Game Dev",
    title: "Survival Game",
    description:
      "A survival game where players must manage resources and survive.",
    url: "https://github.com/topics/survival-game?l=python&o=desc&s=updated",
  },
  {
    id: 19,
    type: "Game Dev",
    title: "Racing Game",
    description: "A racing game with various tracks and vehicles.",
    url: "https://github.com/topics/racing-game?l=python",
  },
  {
    id: 20,
    type: "Game Dev",
    title: "Space Shooter",
    description: "A space shooter game with fast-paced action.",
    url: "https://github.com/alperrkilic/Space-Shooter-Project",
  },
  {
    id: 21,
    type: "Android Dev",
    title: "Weather App",
    description: "An Android app to display weather information.",
    url: "https://www.youtube.com/watch?v=DWZPu0kW2Nk&list=PLgadKTyFdWuhSyMbTAYGV10KK0rU364t4",
  },
  {
    id: 22,
    type: "Android Dev",
    title: "Fitness Tracker",
    description: "An app to track fitness activities and goals.",
    url: "https://github.com/alperrkilic/Space-Shooter-Project",
  },
  {
    id: 23,
    type: "Android Dev",
    title: "Expense Manager",
    description: "An app to manage personal finances and track expenses.",
    url: "https://github.com/neeraj542/Personal-Finance-Tracker",
  },
  {
    id: 24,
    type: "Android Dev",
    title: "Notes App",
    description: "A simple notes app with cloud sync.",
    url: "https://github.com/sbs20/filenotes-android#:~:text=Filenotes%20is%20an%20app%20designed%20for%20simple%20note%20taking%20and%20cloud%20sync.",
  },
  {
    id: 25,
    type: "Android Dev",
    title: "Language Learning App",
    description: "An app to learn new languages with interactive lessons.",
    url: "https://github.com/ikyawthetpaing/euolingo",
  },
  {
    id: 26,
    type: "Android Dev",
    title: "Music Player",
    description: "A music player app with playlists and offline support.",
    url: "https://github.com/OxygenCobalt/Auxio",
  },
  {
    id: 27,
    type: "Android Dev",
    title: "Meditation App",
    description: "An app for guided meditations and relaxation techniques.",
    url: "https://github.com/dhyaan-meditation-app",
  },
  {
    id: 28,
    type: "Android Dev",
    title: "Recipe App",
    description:
      "An app to find and save recipes with a shopping list feature.",
    url: "https://github.com/TomBursch/kitchenowl",
  },
  {
    id: 29,
    type: "Android Dev",
    title: "Travel Planner",
    description: "An app to plan trips and manage travel itineraries.",
    url: "https://github.com/Sanjeev-Kumar78/Travel-Itinerary-Generator",
  },
  {
    id: 30,
    type: "Android Dev",
    title: "Habit Tracker",
    description: "An app to build and track daily habits.",
    url: "https://github.com/iSoron/uhabits",
  },
];
